import assert from 'node:assert/strict';
import { savePlan, listPlans, exportPlan, deletePlan } from './saved-plans.js';
const values = new Map();
const storage = {get length(){return values.size;},key:i=>[...values.keys()][i],getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};
const state = {courses:[{id:'a',courseCode:'CS',section:'1',title:'Algorithms',credits:4,components:[]}],selection:['a']};
savePlan(storage,'Option A',state,'a');
state.selection=[];
savePlan(storage,'Option B',state,'b');
assert.equal(listPlans(storage).plans.length,2);
assert.deepEqual(listPlans(storage).plans.find(p=>p.id==='a').selection,['a']);
assert.throws(()=>savePlan(storage,'Overwrite',state,'a'));
assert.throws(()=>savePlan(storage,' ',state,'c'));
assert.throws(()=>savePlan({...storage,setItem(){throw Error('Quota exceeded');}},'Option C',state,'c'));
assert.equal(listPlans(storage).plans.length,2);
values.set('albert.web.plan.v1.broken','invalid');
assert.equal(listPlans(storage).unreadable,1);
assert.equal(values.get('albert.web.plan.v1.broken'),'invalid');
console.log('Saved plan checks passed: round trip, immutable copies, collision, validation, quota, corrupt data.');
const {defaultConstraints} = await import('../../src/shared/constraints.js');
const original = values.get('albert.web.plan.v1.a');
const legacy = JSON.parse(original); delete legacy.constraints;
values.set('albert.web.plan.v1.a',JSON.stringify(legacy));
assert.deepEqual(listPlans(storage).plans.find(p=>p.id==='a').constraints,defaultConstraints());
assert.equal(values.get('albert.web.plan.v1.a'),JSON.stringify(legacy));
state.constraints={...defaultConstraints(),unavailableDays:['Fri'],lockedCourseIds:['a']};
savePlan(storage,'With rules',state,'rules');
state.constraints.unavailableDays.push('Mon');
assert.deepEqual(listPlans(storage).plans.find(p=>p.id==='rules').constraints.unavailableDays,['Fri']);
assert.deepEqual(listPlans(storage).plans.find(p=>p.id==='rules').constraints.lockedCourseIds,['a']);
console.log('Constraint persistence and non-destructive legacy loading checks passed.');
const exported = JSON.parse(exportPlan(listPlans(storage).plans.find(plan=>plan.id==='rules')));
const {parseBackup} = await import('./import.js');
assert.deepEqual(parseBackup(exported).selection,listPlans(storage).plans.find(plan=>plan.id==='rules').selection);
assert.deepEqual(exported.data.constraints.unavailableDays,['Fri']);
assert.equal(exported.data.name,undefined);
values.set('unrelated','preserve');
deletePlan({...storage,removeItem:key=>values.delete(key)},'rules');
assert.equal(listPlans(storage).plans.some(plan=>plan.id==='rules'),false);
assert.equal(values.get('unrelated'),'preserve');
assert.equal(values.get('albert.web.plan.v1.broken'),'invalid');
assert.throws(()=>deletePlan({removeItem(){throw Error('Unavailable');}},'a'));
